[package]
authors = ["Manuel Mauro <manuel.mauro@protonmail.com>", "Ivan Schuetz <ivanhp978@gmail.com>",]
description = "Core structs for the Algorand blockchain."
edition = "2018"
keywords = ["Algorand", "sdk"]
license = "MIT"
name = "algonaut_core"
repository = "https://github.com/manuelmauro/algonaut"
version = "0.4.2"

[dependencies]
algonaut_crypto = {path = "../algonaut_crypto", version = "0.4.2"}
algonaut_encoding = {path = "../algonaut_encoding", version = "0.4.2"}
data-encoding = "2.11.0"
derive_more = { version = "2.1.1", features = ["add", "display", "from"] }
serde = {version = "1.0", features = ["derive"]}
sha2 = "0.11.0"
static_assertions = "1.1.0"
rmp-serde = "1.3.1"
thiserror = "2.0.18"
ring = "0.17.14"

[dev-dependencies]
rand = "0.8.5"
