[package]
authors = ["Manuel Mauro <manuel.mauro@protonmail.com>", "Ivan Schuetz <ivanhp978@gmail.com>",]
description = "Core structs for the Algorand blockchain."
edition = "2024"
keywords = ["Algorand", "sdk"]
license = "MIT OR Apache-2.0"
name = "algonaut_core"
repository = "https://github.com/manuelmauro/algonaut"
version = "0.7.0"

[dependencies]
algonaut_crypto = { workspace = true }
algonaut_encoding = { workspace = true }
data-encoding = { workspace = true }
derive_more = { workspace = true, features = ["add", "display", "from"] }
rmp-serde = { workspace = true }
serde = { workspace = true }
sha2 = { workspace = true }
static_assertions = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
rand = { workspace = true }
serde_json = { workspace = true }
