[package]
authors = [
    "Manuel Mauro <manuel.mauro@protonmail.com>",
    "Ivan Schuetz <ivanhp978@gmail.com>",
]
description = "Implementation of the Algorand blockchain transaction set."
edition = "2024"
keywords = ["Algorand", "sdk"]
license = "MIT"
name = "algonaut_transaction"
repository = "https://github.com/manuelmauro/algonaut"
version = "0.4.2"

[dependencies]
algonaut_abi = { workspace = true }
algonaut_core = { workspace = true }
algonaut_crypto = { workspace = true }
algonaut_encoding = { workspace = true }
algonaut_model = { workspace = true }
data-encoding = { workspace = true }
derive_more = { workspace = true }
getrandom = { workspace = true, features = ["js"] }
num-bigint = { workspace = true }
num-traits = { workspace = true }
rand = { workspace = true }
ring = { workspace = true }
rmp-serde = { workspace = true }
serde = { workspace = true }
serde_bytes = { workspace = true }
sha2 = { workspace = true }
thiserror = { workspace = true }
url = { workspace = true }
urlencoding = { workspace = true }
