[package]
name = "algonaut_indexer"
version = "0.6.0"
authors = ["OpenAPI Generator team and contributors"]
description = "Algorand ledger analytics API."
# Override this license by providing a License Object in the OpenAPI.
license = "MIT"
edition = "2024"

[dependencies]
algonaut_crypto = { workspace = true }
algonaut_encoding = { workspace = true }
reqwest = { workspace = true, features = ["json", "multipart", "query"] }
serde = { workspace = true }
serde_derive = { workspace = true }
serde_json = { workspace = true }
url = { workspace = true }
uuid = { workspace = true }
