/*
 * Indexer
 *
 * Algorand ledger analytics API.
 *
 * The version of the OpenAPI document: 2.0
 *
 * Generated by: https://openapi-generator.tech
 */

/// Hashtype : The type of hash function used to create the proof, must be one of:  * sha512_256  * sha256

/// The type of hash function used to create the proof, must be one of:  * sha512_256  * sha256
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Hashtype {
    #[serde(rename = "sha512_256")]
    Sha512256,
    #[serde(rename = "sha256")]
    Sha256,
}

impl ToString for Hashtype {
    fn to_string(&self) -> String {
        match self {
            Self::Sha512256 => String::from("sha512_256"),
            Self::Sha256 => String::from("sha256"),
        }
    }
}

impl Default for Hashtype {
    fn default() -> Hashtype {
        Self::Sha512256
    }
}
