/*
 * Indexer
 *
 * Algorand ledger analytics API.
 *
 * The version of the OpenAPI document: 2.0
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct HashFactory {
    /// \\[t\\]
    #[serde(rename = "hash-type", skip_serializing_if = "Option::is_none")]
    pub hash_type: Option<i32>,
}

impl HashFactory {
    pub fn new() -> HashFactory {
        HashFactory { hash_type: None }
    }
}
