/*
 * Indexer
 *
 * Algorand ledger analytics API.
 *
 * The version of the OpenAPI document: 2.0
 *
 * Generated by: https://openapi-generator.tech
 */

use algonaut_encoding::Bytes;

/// HbProofFields : \\[hbprf\\] HbProof is a signature using HeartbeatAddress's partkey, thereby showing it is online.

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct HbProofFields {
    /// \\[p\\] Public key of the heartbeat message.
    #[serde(rename = "hb-pk", skip_serializing_if = "Option::is_none")]
    pub hb_pk: Option<Bytes>,
    /// \\[p1s\\] Signature of OneTimeSignatureSubkeyOffsetID(PK, Batch, Offset) under the key PK2.
    #[serde(rename = "hb-pk1sig", skip_serializing_if = "Option::is_none")]
    pub hb_pk1sig: Option<Bytes>,
    /// \\[p2\\] Key for new-style two-level ephemeral signature.
    #[serde(rename = "hb-pk2", skip_serializing_if = "Option::is_none")]
    pub hb_pk2: Option<Bytes>,
    /// \\[p2s\\] Signature of OneTimeSignatureSubkeyBatchID(PK2, Batch) under the master key (OneTimeSignatureVerifier).
    #[serde(rename = "hb-pk2sig", skip_serializing_if = "Option::is_none")]
    pub hb_pk2sig: Option<Bytes>,
    /// \\[s\\] Signature of the heartbeat message.
    #[serde(rename = "hb-sig", skip_serializing_if = "Option::is_none")]
    pub hb_sig: Option<Bytes>,
}

impl HbProofFields {
    /// \\[hbprf\\] HbProof is a signature using HeartbeatAddress's partkey, thereby showing it is online.
    pub fn new() -> HbProofFields {
        HbProofFields {
            hb_pk: None,
            hb_pk1sig: None,
            hb_pk2: None,
            hb_pk2sig: None,
            hb_sig: None,
        }
    }
}
