/*
 * Indexer
 *
 * Algorand ledger analytics API.
 *
 * The version of the OpenAPI document: 2.0
 *
 * Generated by: https://openapi-generator.tech
 */

/// HealthCheck : A health check response.

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct HealthCheck {
    #[serde(rename = "data", skip_serializing_if = "Option::is_none")]
    pub data: Option<serde_json::Value>,
    #[serde(rename = "db-available")]
    pub db_available: bool,
    #[serde(rename = "errors", skip_serializing_if = "Option::is_none")]
    pub errors: Option<Vec<String>>,
    #[serde(rename = "is-migrating")]
    pub is_migrating: bool,
    #[serde(rename = "message")]
    pub message: String,
    #[serde(rename = "round")]
    pub round: i32,
    /// Current version.
    #[serde(rename = "version")]
    pub version: String,
}

impl HealthCheck {
    /// A health check response.
    pub fn new(
        db_available: bool,
        is_migrating: bool,
        message: String,
        round: i32,
        version: String,
    ) -> HealthCheck {
        HealthCheck {
            data: None,
            db_available,
            errors: None,
            is_migrating,
            message,
            round,
            version,
        }
    }
}
