/*
 * Indexer
 *
 * Algorand ledger analytics API.
 *
 * The version of the OpenAPI document: 2.0
 *
 * Generated by: https://openapi-generator.tech
 */

/// HoldingRef : HoldingRef names a holding by referring to an Address and Asset it belongs to.

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct HoldingRef {
    /// \\[d\\] Address in access list, or the sender of the transaction.
    #[serde(rename = "address")]
    pub address: String,
    /// \\[s\\] Asset ID for asset in access list.
    #[serde(rename = "asset")]
    pub asset: u64,
}

impl HoldingRef {
    /// HoldingRef names a holding by referring to an Address and Asset it belongs to.
    pub fn new(address: String, asset: u64) -> HoldingRef {
        HoldingRef { address, asset }
    }
}
