/*
 * Indexer
 *
 * Algorand ledger analytics API.
 *
 * The version of the OpenAPI document: 2.0
 *
 * Generated by: https://openapi-generator.tech
 */

/// LocalsRef : LocalsRef names a local state by referring to an Address and App it belongs to.

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct LocalsRef {
    /// \\[d\\] Address in access list, or the sender of the transaction.
    #[serde(rename = "address")]
    pub address: String,
    /// \\[p\\] Application ID for app in access list, or zero if referring to the called application.
    #[serde(rename = "app")]
    pub app: u64,
}

impl LocalsRef {
    /// LocalsRef names a local state by referring to an Address and App it belongs to.
    pub fn new(address: String, app: u64) -> LocalsRef {
        LocalsRef { address, app }
    }
}
