/*
 * Indexer
 *
 * Algorand ledger analytics API.
 *
 * The version of the OpenAPI document: 2.0
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct LookupApplicationLogsById200Response {
    /// \\[appidx\\] application index.
    #[serde(rename = "application-id")]
    pub application_id: i32,
    /// Round at which the results were computed.
    #[serde(rename = "current-round")]
    pub current_round: i32,
    #[serde(rename = "log-data", skip_serializing_if = "Option::is_none")]
    pub log_data: Option<Vec<crate::models::ApplicationLogData>>,
    /// Used for pagination, when making another request provide this token with the next parameter.
    #[serde(rename = "next-token", skip_serializing_if = "Option::is_none")]
    pub next_token: Option<String>,
}

impl LookupApplicationLogsById200Response {
    pub fn new(application_id: i32, current_round: i32) -> LookupApplicationLogsById200Response {
        LookupApplicationLogsById200Response {
            application_id,
            current_round,
            log_data: None,
            next_token: None,
        }
    }
}
