/*
 * Indexer
 *
 * Algorand ledger analytics API.
 *
 * The version of the OpenAPI document: 2.0
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct LookupAssetById200Response {
    #[serde(rename = "asset")]
    pub asset: Box<crate::models::Asset>,
    /// Round at which the results were computed.
    #[serde(rename = "current-round")]
    pub current_round: i32,
}

impl LookupAssetById200Response {
    pub fn new(asset: crate::models::Asset, current_round: i32) -> LookupAssetById200Response {
        LookupAssetById200Response {
            asset: Box::new(asset),
            current_round,
        }
    }
}
