/*
 * Indexer
 *
 * Algorand ledger analytics API.
 *
 * The version of the OpenAPI document: 2.0
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct LookupApplicationById200Response {
    #[serde(rename = "application", skip_serializing_if = "Option::is_none")]
    pub application: Option<Box<crate::models::Application>>,
    /// Round at which the results were computed.
    #[serde(rename = "current-round")]
    pub current_round: u64,
}

impl LookupApplicationById200Response {
    pub fn new(current_round: u64) -> LookupApplicationById200Response {
        LookupApplicationById200Response {
            application: None,
            current_round,
        }
    }
}
