/*
 * Indexer
 *
 * Algorand ledger analytics API.
 *
 * The version of the OpenAPI document: 2.0
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct LookupAccountTransactions200Response {
    /// Round at which the results were computed.
    #[serde(rename = "current-round")]
    pub current_round: u64,
    /// Used for pagination, when making another request provide this token with the next parameter.
    #[serde(rename = "next-token", skip_serializing_if = "Option::is_none")]
    pub next_token: Option<String>,
    #[serde(rename = "transactions")]
    pub transactions: Vec<crate::models::Transaction>,
}

impl LookupAccountTransactions200Response {
    pub fn new(
        current_round: u64,
        transactions: Vec<crate::models::Transaction>,
    ) -> LookupAccountTransactions200Response {
        LookupAccountTransactions200Response {
            current_round,
            next_token: None,
            transactions,
        }
    }
}
