/*
 * Indexer
 *
 * Algorand ledger analytics API.
 *
 * The version of the OpenAPI document: 2.0
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct LookupAccountAssets200Response {
    #[serde(rename = "assets")]
    pub assets: Vec<crate::models::AssetHolding>,
    /// Round at which the results were computed.
    #[serde(rename = "current-round")]
    pub current_round: i32,
    /// Used for pagination, when making another request provide this token with the next parameter.
    #[serde(rename = "next-token", skip_serializing_if = "Option::is_none")]
    pub next_token: Option<String>,
}

impl LookupAccountAssets200Response {
    pub fn new(
        assets: Vec<crate::models::AssetHolding>,
        current_round: i32,
    ) -> LookupAccountAssets200Response {
        LookupAccountAssets200Response {
            assets,
            current_round,
            next_token: None,
        }
    }
}
