/*
 * Indexer
 *
 * Algorand ledger analytics API.
 *
 * The version of the OpenAPI document: 2.0
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct LookupAccountAppLocalStates200Response {
    #[serde(rename = "apps-local-states")]
    pub apps_local_states: Vec<crate::models::ApplicationLocalState>,
    /// Round at which the results were computed.
    #[serde(rename = "current-round")]
    pub current_round: i32,
    /// Used for pagination, when making another request provide this token with the next parameter.
    #[serde(rename = "next-token", skip_serializing_if = "Option::is_none")]
    pub next_token: Option<String>,
}

impl LookupAccountAppLocalStates200Response {
    pub fn new(
        apps_local_states: Vec<crate::models::ApplicationLocalState>,
        current_round: i32,
    ) -> LookupAccountAppLocalStates200Response {
        LookupAccountAppLocalStates200Response {
            apps_local_states,
            current_round,
            next_token: None,
        }
    }
}
