/*
 * Indexer
 *
 * Algorand ledger analytics API.
 *
 * The version of the OpenAPI document: 2.0
 *
 * Generated by: https://openapi-generator.tech
 */

/// MiniAssetHolding : A simplified version of AssetHolding

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct MiniAssetHolding {
    #[serde(rename = "address")]
    pub address: String,
    #[serde(rename = "amount")]
    pub amount: i32,
    /// Whether or not this asset holding is currently deleted from its account.
    #[serde(rename = "deleted", skip_serializing_if = "Option::is_none")]
    pub deleted: Option<bool>,
    #[serde(rename = "is-frozen")]
    pub is_frozen: bool,
    /// Round during which the account opted into the asset.
    #[serde(rename = "opted-in-at-round", skip_serializing_if = "Option::is_none")]
    pub opted_in_at_round: Option<i32>,
    /// Round during which the account opted out of the asset.
    #[serde(rename = "opted-out-at-round", skip_serializing_if = "Option::is_none")]
    pub opted_out_at_round: Option<i32>,
}

impl MiniAssetHolding {
    /// A simplified version of AssetHolding
    pub fn new(address: String, amount: i32, is_frozen: bool) -> MiniAssetHolding {
        MiniAssetHolding {
            address,
            amount,
            deleted: None,
            is_frozen,
            opted_in_at_round: None,
            opted_out_at_round: None,
        }
    }
}
