/*
 * Indexer
 *
 * Algorand ledger analytics API.
 *
 * The version of the OpenAPI document: 2.0
 *
 * Generated by: https://openapi-generator.tech
 */

/// ParticipationUpdates : Participation account data that needs to be checked/acted on by the network.

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ParticipationUpdates {
    /// \\[partupdrmv\\] a list of online accounts that needs to be converted to offline since their participation key expired.
    #[serde(
        rename = "expired-participation-accounts",
        skip_serializing_if = "Option::is_none"
    )]
    pub expired_participation_accounts: Option<Vec<String>>,
}

impl ParticipationUpdates {
    /// Participation account data that needs to be checked/acted on by the network.
    pub fn new() -> ParticipationUpdates {
        ParticipationUpdates {
            expired_participation_accounts: None,
        }
    }
}
