/*
 * Indexer
 *
 * Algorand ledger analytics API.
 *
 * The version of the OpenAPI document: 2.0
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct SearchForApplicationBoxes200Response {
    /// \\[appidx\\] application index.
    #[serde(rename = "application-id")]
    pub application_id: i32,
    #[serde(rename = "boxes")]
    pub boxes: Vec<crate::models::BoxDescriptor>,
    /// Used for pagination, when making another request provide this token with the next parameter.
    #[serde(rename = "next-token", skip_serializing_if = "Option::is_none")]
    pub next_token: Option<String>,
}

impl SearchForApplicationBoxes200Response {
    pub fn new(
        application_id: i32,
        boxes: Vec<crate::models::BoxDescriptor>,
    ) -> SearchForApplicationBoxes200Response {
        SearchForApplicationBoxes200Response {
            application_id,
            boxes,
            next_token: None,
        }
    }
}
