/*
 * Indexer
 *
 * Algorand ledger analytics API.
 *
 * The version of the OpenAPI document: 2.0
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct SearchForAccounts400Response {
    #[serde(rename = "data", skip_serializing_if = "Option::is_none")]
    pub data: Option<serde_json::Value>,
    #[serde(rename = "message")]
    pub message: String,
}

impl SearchForAccounts400Response {
    pub fn new(message: String) -> SearchForAccounts400Response {
        SearchForAccounts400Response {
            data: None,
            message,
        }
    }
}
