/*
 * Indexer
 *
 * Algorand ledger analytics API.
 *
 * The version of the OpenAPI document: 2.0
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct StateProofVerifier {
    /// \\[cmt\\] Represents the root of the vector commitment tree.
    #[serde(rename = "commitment", skip_serializing_if = "Option::is_none")]
    pub commitment: Option<String>,
    /// \\[lf\\] Key lifetime.
    #[serde(rename = "key-lifetime", skip_serializing_if = "Option::is_none")]
    pub key_lifetime: Option<i32>,
}

impl StateProofVerifier {
    pub fn new() -> StateProofVerifier {
        StateProofVerifier {
            commitment: None,
            key_lifetime: None,
        }
    }
}
