/*
 * Indexer
 *
 * Algorand ledger analytics API.
 *
 * The version of the OpenAPI document: 2.0
 *
 * Generated by: https://openapi-generator.tech
 */

/// TransactionAssetConfig : Fields for asset allocation, re-configuration, and destruction.   A zero value for asset-id indicates asset creation. A zero value for the params indicates asset destruction.  Definition: data/transactions/asset.go : AssetConfigTxnFields

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct TransactionAssetConfig {
    /// \\[xaid\\] ID of the asset being configured or empty if creating.
    #[serde(rename = "asset-id", skip_serializing_if = "Option::is_none")]
    pub asset_id: Option<i32>,
    #[serde(rename = "params", skip_serializing_if = "Option::is_none")]
    pub params: Option<Box<crate::models::AssetParams>>,
}

impl TransactionAssetConfig {
    /// Fields for asset allocation, re-configuration, and destruction.   A zero value for asset-id indicates asset creation. A zero value for the params indicates asset destruction.  Definition: data/transactions/asset.go : AssetConfigTxnFields
    pub fn new() -> TransactionAssetConfig {
        TransactionAssetConfig {
            asset_id: None,
            params: None,
        }
    }
}
