/*
 * Indexer
 *
 * Algorand ledger analytics API.
 *
 * The version of the OpenAPI document: 2.0
 *
 * Generated by: https://openapi-generator.tech
 */

/// TransactionSignature : Validation signature associated with some data. Only one of the signatures should be provided.

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct TransactionSignature {
    #[serde(rename = "logicsig", skip_serializing_if = "Option::is_none")]
    pub logicsig: Option<Box<crate::models::TransactionSignatureLogicsig>>,
    #[serde(rename = "multisig", skip_serializing_if = "Option::is_none")]
    pub multisig: Option<Box<crate::models::TransactionSignatureMultisig>>,
    /// \\[sig\\] Standard ed25519 signature.
    #[serde(rename = "sig", skip_serializing_if = "Option::is_none")]
    pub sig: Option<String>,
}

impl TransactionSignature {
    /// Validation signature associated with some data. Only one of the signatures should be provided.
    pub fn new() -> TransactionSignature {
        TransactionSignature {
            logicsig: None,
            multisig: None,
            sig: None,
        }
    }
}
