/*
 * Algod REST API.
 *
 * API endpoint for algod operations.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: contact@algorand.com
 * Generated by: https://openapi-generator.tech
 */

/// AbortCatchup200Response : An catchpoint abort response.

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct AbortCatchup200Response {
    /// Catchup abort response string
    #[serde(rename = "catchup-message")]
    pub catchup_message: String,
}

impl AbortCatchup200Response {
    /// An catchpoint abort response.
    pub fn new(catchup_message: String) -> AbortCatchup200Response {
        AbortCatchup200Response { catchup_message }
    }
}
