/*
 * Algod REST API.
 *
 * API endpoint for algod operations.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: contact@algorand.com
 * Generated by: https://openapi-generator.tech
 */

/// AccountApplicationResource : AccountApplicationResource describes the account's application resource (local state and params if the account is the creator) for a specific application ID.

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct AccountApplicationResource {
    #[serde(rename = "app-local-state", skip_serializing_if = "Option::is_none")]
    pub app_local_state: Option<Box<crate::models::ApplicationLocalState>>,
    /// Round when the account opted into or created the application.
    #[serde(rename = "created-at-round", skip_serializing_if = "Option::is_none")]
    pub created_at_round: Option<u64>,
    /// Whether the application has been deleted.
    #[serde(rename = "deleted", skip_serializing_if = "Option::is_none")]
    pub deleted: Option<bool>,
    /// The application ID.
    #[serde(rename = "id")]
    pub id: u64,
    #[serde(rename = "params", skip_serializing_if = "Option::is_none")]
    pub params: Option<Box<crate::models::ApplicationParams>>,
}

impl AccountApplicationResource {
    /// AccountApplicationResource describes the account's application resource (local state and params if the account is the creator) for a specific application ID.
    pub fn new(id: u64) -> AccountApplicationResource {
        AccountApplicationResource {
            app_local_state: None,
            created_at_round: None,
            deleted: None,
            id,
            params: None,
        }
    }
}
