/*
 * Algod REST API.
 *
 * API endpoint for algod operations.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: contact@algorand.com
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct AccountApplicationInformation200Response {
    #[serde(rename = "app-local-state", skip_serializing_if = "Option::is_none")]
    pub app_local_state: Option<Box<crate::models::ApplicationLocalState>>,
    #[serde(rename = "created-app", skip_serializing_if = "Option::is_none")]
    pub created_app: Option<Box<crate::models::ApplicationParams>>,
    /// The round for which this information is relevant.
    #[serde(rename = "round")]
    pub round: u64,
}

impl AccountApplicationInformation200Response {
    pub fn new(round: u64) -> AccountApplicationInformation200Response {
        AccountApplicationInformation200Response {
            app_local_state: None,
            created_app: None,
            round,
        }
    }
}
