/*
 * Algod REST API.
 *
 * API endpoint for algod operations.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: contact@algorand.com
 * Generated by: https://openapi-generator.tech
 */

/// ApplicationStateSchema : Specifies maximums on the number of each type that may be stored.

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ApplicationStateSchema {
    /// \\[nbs\\] num of byte slices.
    #[serde(rename = "num-byte-slice")]
    pub num_byte_slice: u64,
    /// \\[nui\\] num of uints.
    #[serde(rename = "num-uint")]
    pub num_uint: u64,
}

impl ApplicationStateSchema {
    /// Specifies maximums on the number of each type that may be stored.
    pub fn new(num_byte_slice: u64, num_uint: u64) -> ApplicationStateSchema {
        ApplicationStateSchema {
            num_byte_slice,
            num_uint,
        }
    }
}
