/*
 * Algod REST API.
 *
 * API endpoint for algod operations.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: contact@algorand.com
 * Generated by: https://openapi-generator.tech
 */

/// BoxDescriptor : Box descriptor describes a Box.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct BoxDescriptor {
    /// Base64 encoded box name
    #[serde(rename = "name")]
    pub name: String,
}

impl BoxDescriptor {
    /// Box descriptor describes a Box.
    pub fn new(name: String) -> BoxDescriptor {
        BoxDescriptor {
            name,
        }
    }
}


