/*
 * Algod REST API.
 *
 * API endpoint for algod operations.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: contact@algorand.com
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct GetBlockTxids200Response {
    /// Block transaction IDs.
    #[serde(rename = "blockTxids")]
    pub block_txids: Vec<String>,
}

impl GetBlockTxids200Response {
    pub fn new(block_txids: Vec<String>) -> GetBlockTxids200Response {
        GetBlockTxids200Response { block_txids }
    }
}
