/*
 * Algod REST API.
 *
 * API endpoint for algod operations.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: contact@algorand.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct GetSyncRound200Response {
    /// The minimum sync round for the ledger.
    #[serde(rename = "round")]
    pub round: i32,
}

impl GetSyncRound200Response {
    pub fn new(round: i32) -> GetSyncRound200Response {
        GetSyncRound200Response {
            round,
        }
    }
}


