/*
 * Algod REST API.
 *
 * API endpoint for algod operations.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: contact@algorand.com
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct GetTransactionGroupLedgerStateDeltasForRound200Response {
    #[serde(rename = "Deltas")]
    pub deltas: Vec<crate::models::LedgerStateDeltaForTransactionGroup>,
}

impl GetTransactionGroupLedgerStateDeltasForRound200Response {
    pub fn new(
        deltas: Vec<crate::models::LedgerStateDeltaForTransactionGroup>,
    ) -> GetTransactionGroupLedgerStateDeltasForRound200Response {
        GetTransactionGroupLedgerStateDeltasForRound200Response { deltas }
    }
}
