/*
 * Algod REST API.
 *
 * API endpoint for algod operations.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: contact@algorand.com
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct GetBlockTimeStampOffset200Response {
    /// Timestamp offset in seconds.
    #[serde(rename = "offset")]
    pub offset: u64,
}

impl GetBlockTimeStampOffset200Response {
    pub fn new(offset: u64) -> GetBlockTimeStampOffset200Response {
        GetBlockTimeStampOffset200Response { offset }
    }
}
