/*
 * Algod REST API.
 *
 * API endpoint for algod operations.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: contact@algorand.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct GetApplicationBoxes200Response {
    #[serde(rename = "boxes")]
    pub boxes: Vec<crate::models::BoxDescriptor>,
}

impl GetApplicationBoxes200Response {
    pub fn new(boxes: Vec<crate::models::BoxDescriptor>) -> GetApplicationBoxes200Response {
        GetApplicationBoxes200Response {
            boxes,
        }
    }
}


