/*
 * Algod REST API.
 *
 * API endpoint for algod operations.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: contact@algorand.com
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct GetBlockLogs200Response {
    #[serde(rename = "logs")]
    pub logs: Vec<crate::models::AppCallLogs>,
}

impl GetBlockLogs200Response {
    pub fn new(logs: Vec<crate::models::AppCallLogs>) -> GetBlockLogs200Response {
        GetBlockLogs200Response { logs }
    }
}
