/*
 * Algod REST API.
 *
 * API endpoint for algod operations.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: contact@algorand.com
 * Generated by: https://openapi-generator.tech
 */

/// KvDelta : A single Delta containing the key, the previous value and the current value for a single round.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct KvDelta {
    /// The key, base64 encoded.
    #[serde(rename = "key", skip_serializing_if = "Option::is_none")]
    pub key: Option<String>,
    /// The new value of the KV store entry, base64 encoded.
    #[serde(rename = "value", skip_serializing_if = "Option::is_none")]
    pub value: Option<String>,
}

impl KvDelta {
    /// A single Delta containing the key, the previous value and the current value for a single round.
    pub fn new() -> KvDelta {
        KvDelta {
            key: None,
            value: None,
        }
    }
}


