/*
 * Algod REST API.
 *
 * API endpoint for algod operations.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: contact@algorand.com
 * Generated by: https://openapi-generator.tech
 */

use algonaut_encoding::Bytes;

/// Box : Box name and its content.

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct Box {
    /// \\[name\\] box name, base64 encoded
    #[serde(rename = "name")]
    pub name: Bytes,
    /// \\[value\\] box value, base64 encoded.
    #[serde(rename = "value")]
    pub value: Bytes,
}

impl Box {
    /// Box name and its content.
    pub fn new(name: Bytes, value: Bytes) -> Box {
        Box { name, value }
    }
}
