/*
 * Algod REST API.
 *
 * API endpoint for algod operations.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: contact@algorand.com
 * Generated by: https://openapi-generator.tech
 */

/// SimulateRequestTransactionGroup : A transaction group to simulate.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct SimulateRequestTransactionGroup {
    /// An atomic transaction group.
    #[serde(rename = "txns")]
    pub txns: Vec<String>,
}

impl SimulateRequestTransactionGroup {
    /// A transaction group to simulate.
    pub fn new(txns: Vec<String>) -> SimulateRequestTransactionGroup {
        SimulateRequestTransactionGroup {
            txns,
        }
    }
}


