/*
 * Algod REST API.
 *
 * API endpoint for algod operations.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: contact@algorand.com
 * Generated by: https://openapi-generator.tech
 */

/// StartCatchup200Response : An catchpoint start response.

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct StartCatchup200Response {
    /// Catchup start response string
    #[serde(rename = "catchup-message")]
    pub catchup_message: String,
}

impl StartCatchup200Response {
    /// An catchpoint start response.
    pub fn new(catchup_message: String) -> StartCatchup200Response {
        StartCatchup200Response { catchup_message }
    }
}
