/*
 * Algod REST API.
 *
 * API endpoint for algod operations.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: contact@algorand.com
 * Generated by: https://openapi-generator.tech
 */

/// StateProof : Represents a state proof and its corresponding message



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct StateProof {
    #[serde(rename = "Message")]
    pub message: Box<crate::models::StateProofMessage>,
    /// The encoded StateProof for the message.
    #[serde(rename = "StateProof")]
    pub state_proof: String,
}

impl StateProof {
    /// Represents a state proof and its corresponding message
    pub fn new(message: crate::models::StateProofMessage, state_proof: String) -> StateProof {
        StateProof {
            message: Box::new(message),
            state_proof,
        }
    }
}


