/*
 * Algod REST API.
 *
 * API endpoint for algod operations.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: contact@algorand.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct TealCompile200Response {
    /// base32 SHA512_256 of program bytes (Address style)
    #[serde(rename = "hash")]
    pub hash: String,
    /// base64 encoded program bytes
    #[serde(rename = "result")]
    pub result: String,
    /// JSON of the source map
    #[serde(rename = "sourcemap", skip_serializing_if = "Option::is_none")]
    pub sourcemap: Option<serde_json::Value>,
}

impl TealCompile200Response {
    pub fn new(hash: String, result: String) -> TealCompile200Response {
        TealCompile200Response {
            hash,
            result,
            sourcemap: None,
        }
    }
}


