/*
 * Algod REST API.
 *
 * API endpoint for algod operations.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: contact@algorand.com
 * Generated by: https://openapi-generator.tech
 */

/// TealKeyValue : Represents a key-value pair in an application store.

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct TealKeyValue {
    #[serde(rename = "key")]
    pub key: String,
    #[serde(rename = "value")]
    pub value: Box<crate::models::TealValue>,
}

impl TealKeyValue {
    /// Represents a key-value pair in an application store.
    pub fn new(key: String, value: crate::models::TealValue) -> TealKeyValue {
        TealKeyValue {
            key,
            value: Box::new(value),
        }
    }
}
