[package]
authors = [
    "Manuel Mauro <manuel.mauro@protonmail.com>",
    "Ivan Schuetz <ivanhp978@gmail.com>",
]
description = "Crypto utilities for the Algorand blockchain."
edition = "2024"
keywords = ["Algorand", "sdk"]
license = "MIT"
name = "algonaut_crypto"
repository = "https://github.com/manuelmauro/algonaut"
version = "0.4.2"

[dependencies]
algonaut_encoding = { workspace = true }
data-encoding = { workspace = true }
derive_more = { workspace = true, features = ["display", "from"] }
indexmap = { workspace = true }
lazy_static = { workspace = true }
ring = { workspace = true }
serde = { workspace = true }
sha2 = { workspace = true }
static_assertions = { workspace = true }
thiserror = { workspace = true }
