[package]
authors = ["Manuel Mauro <manuel.mauro@protonmail.com>", "Ivan Schuetz <ivanhp978@gmail.com>",]
description = "Encoding utilities for the Algorand blockchain."
edition = "2024"
keywords = ["Algorand", "sdk"]
license = "MIT"
name = "algonaut_encoding"
repository = "https://github.com/manuelmauro/algonaut"
version = "0.6.0"

[dependencies]
data-encoding = { workspace = true }
serde = { workspace = true }
