[package]
name = "algonaut_algod"
version = "0.6.0"
authors = ["contact@algorand.com"]
description = "API endpoint for algod operations."
# Override this license by providing a License Object in the OpenAPI.
license = "MIT"
edition = "2024"

[dependencies]
algonaut_crypto = { workspace = true }
algonaut_encoding = { workspace = true }
algonaut_model = { workspace = true }
algonaut_transaction = { workspace = true }
reqwest = { workspace = true, features = ["json", "multipart", "query"] }
serde = { workspace = true }
serde_derive = { workspace = true }
serde_json = { workspace = true }
url = { workspace = true }
uuid = { workspace = true }
