/*
 * Indexer
 *
 * Algorand ledger analytics API.
 *
 * The version of the OpenAPI document: 2.0
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct AccountsResponse {
    #[serde(rename = "accounts")]
    pub accounts: Vec<crate::indexer::Account>,
    /// Round at which the results were computed.
    #[serde(rename = "current-round")]
    pub current_round: u64,
    /// Used for pagination, when making another request provide this token with the next parameter.
    #[serde(rename = "next-token", skip_serializing_if = "Option::is_none")]
    pub next_token: Option<String>,
}

impl AccountsResponse {
    pub fn new(accounts: Vec<crate::indexer::Account>, current_round: u64) -> AccountsResponse {
        AccountsResponse {
            accounts,
            current_round,
            next_token: None,
        }
    }
}
