/*
 * Indexer
 *
 * Algorand ledger analytics API.
 *
 * The version of the OpenAPI document: 2.0
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ApplicationLogsResponse {
    /// \\[appidx\\] application index.
    #[serde(rename = "application-id")]
    pub application_id: u64,
    /// Round at which the results were computed.
    #[serde(rename = "current-round")]
    pub current_round: u64,
    #[serde(rename = "log-data", skip_serializing_if = "Option::is_none")]
    pub log_data: Option<Vec<crate::indexer::ApplicationLogData>>,
    /// Used for pagination, when making another request provide this token with the next parameter.
    #[serde(rename = "next-token", skip_serializing_if = "Option::is_none")]
    pub next_token: Option<String>,
}

impl ApplicationLogsResponse {
    pub fn new(application_id: u64, current_round: u64) -> ApplicationLogsResponse {
        ApplicationLogsResponse {
            application_id,
            current_round,
            log_data: None,
            next_token: None,
        }
    }
}
