/*
 * Indexer
 *
 * Algorand ledger analytics API.
 *
 * The version of the OpenAPI document: 2.0
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ApplicationBoxesResponse {
    /// \\[appidx\\] application index.
    #[serde(rename = "application-id")]
    pub application_id: u64,
    #[serde(rename = "boxes")]
    pub boxes: Vec<crate::indexer::BoxDescriptor>,
    /// Used for pagination, when making another request provide this token with the next parameter.
    #[serde(rename = "next-token", skip_serializing_if = "Option::is_none")]
    pub next_token: Option<String>,
}

impl ApplicationBoxesResponse {
    pub fn new(
        application_id: u64,
        boxes: Vec<crate::indexer::BoxDescriptor>,
    ) -> ApplicationBoxesResponse {
        ApplicationBoxesResponse {
            application_id,
            boxes,
            next_token: None,
        }
    }
}
