/*
 * Indexer
 *
 * Algorand ledger analytics API.
 *
 * The version of the OpenAPI document: 2.0
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct AssetResponse {
    #[serde(rename = "asset")]
    pub asset: Box<crate::indexer::Asset>,
    /// Round at which the results were computed.
    #[serde(rename = "current-round")]
    pub current_round: u64,
}

impl AssetResponse {
    pub fn new(asset: crate::indexer::Asset, current_round: u64) -> AssetResponse {
        AssetResponse {
            asset: Box::new(asset),
            current_round,
        }
    }
}
