/*
 * Indexer
 *
 * Algorand ledger analytics API.
 *
 * The version of the OpenAPI document: 2.0
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct BlockHeadersResponse {
    #[serde(rename = "blocks")]
    pub blocks: Vec<crate::indexer::Block>,
    /// Round at which the results were computed.
    #[serde(rename = "current-round")]
    pub current_round: u64,
    /// Used for pagination, when making another request provide this token with the next parameter.
    #[serde(rename = "next-token", skip_serializing_if = "Option::is_none")]
    pub next_token: Option<String>,
}

impl BlockHeadersResponse {
    pub fn new(blocks: Vec<crate::indexer::Block>, current_round: u64) -> BlockHeadersResponse {
        BlockHeadersResponse {
            blocks,
            current_round,
            next_token: None,
        }
    }
}
