/*
 * Indexer
 *
 * Algorand ledger analytics API.
 *
 * The version of the OpenAPI document: 2.0
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

/// The type of hash function used to create the proof, must be one of:  * sha512_256  * sha256
#[derive(
    Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize, Default,
)]
pub enum Hashtype {
    #[serde(rename = "sha512_256")]
    #[default]
    Sha512256,
    #[serde(rename = "sha256")]
    Sha256,
}

impl std::fmt::Display for Hashtype {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::Sha512256 => write!(f, "sha512_256"),
            Self::Sha256 => write!(f, "sha256"),
        }
    }
}
