/*
 * Indexer
 *
 * Algorand ledger analytics API.
 *
 * The version of the OpenAPI document: 2.0
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct TransactionResponse {
    /// Round at which the results were computed.
    #[serde(rename = "current-round")]
    pub current_round: u64,
    #[serde(rename = "transaction")]
    pub transaction: Box<crate::indexer::Transaction>,
}

impl TransactionResponse {
    pub fn new(
        current_round: u64,
        transaction: crate::indexer::Transaction,
    ) -> TransactionResponse {
        TransactionResponse {
            current_round,
            transaction: Box::new(transaction),
        }
    }
}
