[package]
authors = [
    "Manuel Mauro <manuel.mauro@protonmail.com>",
    "Ivan Schuetz <ivanhp978@gmail.com>",
]
description = "Model objects"
edition = "2024"
keywords = ["Algorand", "sdk"]
license = "MIT OR Apache-2.0"
name = "algonaut_model"
repository = "https://github.com/manuelmauro/algonaut"
version = "0.9.0"

[dependencies]
algonaut_core = { workspace = true }
algonaut_crypto = { workspace = true }
algonaut_encoding = { workspace = true }
data-encoding = { workspace = true }
serde = { workspace = true }
serde_bytes = { workspace = true }
serde_json = { workspace = true }
serde_with = { workspace = true }
