/*
 * Algod REST API.
 *
 * API endpoint for algod operations.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: contact@algorand.com
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct AccountApplicationInformation {
    #[serde(rename = "app-local-state", skip_serializing_if = "Option::is_none")]
    pub app_local_state: Option<Box<crate::algod::ApplicationLocalState>>,
    #[serde(rename = "created-app", skip_serializing_if = "Option::is_none")]
    pub created_app: Option<Box<crate::algod::ApplicationParams>>,
    /// The round for which this information is relevant.
    #[serde(rename = "round")]
    pub round: u64,
}

impl AccountApplicationInformation {
    pub fn new(round: u64) -> AccountApplicationInformation {
        AccountApplicationInformation {
            app_local_state: None,
            created_app: None,
            round,
        }
    }
}
