/*
 * Algod REST API.
 *
 * API endpoint for algod operations.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: contact@algorand.com
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

/// Asset : Specifies both the unique identifier and the parameters for an asset

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct Asset {
    /// unique asset identifier
    #[serde(rename = "index")]
    pub index: u64,
    #[serde(rename = "params")]
    pub params: Box<crate::algod::AssetParams>,
}

impl Asset {
    /// Specifies both the unique identifier and the parameters for an asset
    pub fn new(index: u64, params: crate::algod::AssetParams) -> Asset {
        Asset {
            index,
            params: Box::new(params),
        }
    }
}
