/*
 * Algod REST API.
 *
 * API endpoint for algod operations.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: contact@algorand.com
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct BlockLogs {
    #[serde(rename = "logs")]
    pub logs: Vec<crate::algod::AppCallLogs>,
}

impl BlockLogs {
    pub fn new(logs: Vec<crate::algod::AppCallLogs>) -> BlockLogs {
        BlockLogs { logs }
    }
}
