/*
 * Algod REST API.
 *
 * API endpoint for algod operations.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: contact@algorand.com
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct BlockHash {
    /// Block header hash.
    #[serde(rename = "blockHash")]
    pub block_hash: String,
}

impl BlockHash {
    pub fn new(block_hash: String) -> BlockHash {
        BlockHash { block_hash }
    }
}
