/*
 * Algod REST API.
 *
 * API endpoint for algod operations.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: contact@algorand.com
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct BlockTimestampOffset {
    /// Timestamp offset in seconds.
    #[serde(rename = "offset")]
    pub offset: u64,
}

impl BlockTimestampOffset {
    pub fn new(offset: u64) -> BlockTimestampOffset {
        BlockTimestampOffset { offset }
    }
}
