/*
 * Algod REST API.
 *
 * API endpoint for algod operations.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: contact@algorand.com
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

/// CatchupStartResponse : An catchpoint start response.

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct CatchupStartResponse {
    /// Catchup start response string
    #[serde(rename = "catchup-message")]
    pub catchup_message: String,
}

impl CatchupStartResponse {
    /// An catchpoint start response.
    pub fn new(catchup_message: String) -> CatchupStartResponse {
        CatchupStartResponse { catchup_message }
    }
}
