/*
 * Algod REST API.
 *
 * API endpoint for algod operations.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: contact@algorand.com
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

/// CatchupAbortResponse : An catchpoint abort response.

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct CatchupAbortResponse {
    /// Catchup abort response string
    #[serde(rename = "catchup-message")]
    pub catchup_message: String,
}

impl CatchupAbortResponse {
    /// An catchpoint abort response.
    pub fn new(catchup_message: String) -> CatchupAbortResponse {
        CatchupAbortResponse { catchup_message }
    }
}
