/*
 * Algod REST API.
 *
 * API endpoint for algod operations.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: contact@algorand.com
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct DisassembledTeal {
    /// disassembled Teal code
    #[serde(rename = "result")]
    pub result: String,
}

impl DisassembledTeal {
    pub fn new(result: String) -> DisassembledTeal {
        DisassembledTeal { result }
    }
}
