/*
 * Algod REST API.
 *
 * API endpoint for algod operations.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: contact@algorand.com
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

/// LedgerStateDeltaForTransactionGroup : Contains a ledger delta for a single transaction group

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct LedgerStateDeltaForTransactionGroup {
    /// Ledger StateDelta object
    #[serde(rename = "Delta")]
    pub delta: serde_json::Value,
    #[serde(rename = "Ids")]
    pub ids: Vec<String>,
}

impl LedgerStateDeltaForTransactionGroup {
    /// Contains a ledger delta for a single transaction group
    pub fn new(delta: serde_json::Value, ids: Vec<String>) -> LedgerStateDeltaForTransactionGroup {
        LedgerStateDeltaForTransactionGroup { delta, ids }
    }
}
