/*
 * Algod REST API.
 *
 * API endpoint for algod operations.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: contact@algorand.com
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ParticipationKeyId {
    /// encoding of the participation ID.
    #[serde(rename = "partId")]
    pub part_id: String,
}

impl ParticipationKeyId {
    pub fn new(part_id: String) -> ParticipationKeyId {
        ParticipationKeyId { part_id }
    }
}
