/*
 * Algod REST API.
 *
 * API endpoint for algod operations.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: contact@algorand.com
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

/// PendingTransactions : PendingTransactions is an array of signed transactions exactly as they were submitted.

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct PendingTransactions {
    /// An array of signed transaction objects.
    #[serde(rename = "top-transactions")]
    pub top_transactions: Vec<crate::algod::ext::transaction::TransactionHeader>,
    /// Total number of transactions in the pool.
    #[serde(rename = "total-transactions")]
    pub total_transactions: u64,
}

impl PendingTransactions {
    /// PendingTransactions is an array of signed transactions exactly as they were submitted.
    pub fn new(
        top_transactions: Vec<crate::algod::ext::transaction::TransactionHeader>,
        total_transactions: u64,
    ) -> PendingTransactions {
        PendingTransactions {
            top_transactions,
            total_transactions,
        }
    }
}
