/*
 * Algod REST API.
 *
 * API endpoint for algod operations.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: contact@algorand.com
 * Generated by: https://openapi-generator.tech
 *
 * Renamed from the generated `GetSupply200Response` and given domain-typed
 * fields via `openapi/type-overrides.json` (D5 of ADR
 * relocate-generated-models). Replaces the hand-written
 * `client_types::Supply` wrapper.
 */

use serde::{Deserialize, Serialize};

use algonaut_core::{MicroAlgos, Round};

/// Supply : Supply represents the current supply of MicroAlgos in the system

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct Supply {
    /// Round
    #[serde(rename = "current_round")]
    pub current_round: Round,
    /// OnlineMoney
    #[serde(rename = "online-money")]
    pub online_money: MicroAlgos,
    /// TotalMoney
    #[serde(rename = "total-money")]
    pub total_money: MicroAlgos,
}

impl Supply {
    /// Supply represents the current supply of MicroAlgos in the system
    pub fn new(current_round: Round, online_money: MicroAlgos, total_money: MicroAlgos) -> Supply {
        Supply {
            current_round,
            online_money,
            total_money,
        }
    }
}
