/*
 * Algod REST API.
 *
 * API endpoint for algod operations.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: contact@algorand.com
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct TransactionGroupStateDeltas {
    #[serde(rename = "Deltas")]
    pub deltas: Vec<crate::algod::LedgerStateDeltaForTransactionGroup>,
}

impl TransactionGroupStateDeltas {
    pub fn new(
        deltas: Vec<crate::algod::LedgerStateDeltaForTransactionGroup>,
    ) -> TransactionGroupStateDeltas {
        TransactionGroupStateDeltas { deltas }
    }
}
