[package]
authors = ["Manuel Mauro <manuel.mauro@protonmail.com>", "Ivan Schuetz <ivanhp978@gmail.com>",]
description = "Application Binary Interface (ABI) to invoke smart contract methods with a standarized interface."
edition = "2024"
keywords = ["Algorand", "sdk"]
license = "MIT OR Apache-2.0"
name = "algonaut_abi"
repository = "https://github.com/manuelmauro/algonaut"
version = "0.9.0"

[dependencies]
algonaut_abi_macros = { workspace = true }
algonaut_abi_model = { workspace = true }
algonaut_abi_sig = { workspace = true }
algonaut_core = { workspace = true }
base64 = { workspace = true }
derive_more = { workspace = true, features = ["display", "from"] }
num-bigint = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
sha2 = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
num-bigint = { workspace = true, features = ["rand"] }
rand = { workspace = true }
